### ISSUE TITLE
Missing reference in compressed (gz) bundle

### ISSUE THREAD

**Issue by dskvr** [dskvr/nostr-watch#262]
**Describe the bug**
```
Uncaught TypeError: Cannot read properties of undefined (reading 'Q_')
    at 76318 (user.js:7:29)
    at n (bootstrap:19:32)
    at 93918 (chunk-common.e20e6cadeeaeb365.bundle.js:1:119281)
    at n (bootstrap:19:32)
    at 9622 (relaysFind.e20e6cadeeaeb365.bundle.js:1:71)
    at n (bootstrap:19:32)
    at startup:4:90
    at n.O (chunk loaded:25:12)
    at startup:5:43
    at relaysFind.e20e6cadeeaeb365.bundle.js:1:5632
```

**To Reproduce**
n/a

**Expected behavior**
No TypeErrors.

**Additional context**
The error occurs in a lightly used data store, and all functionality around that datastore is functional. My guess is that there is a loose reference and the reference was lost during tree shaking.

**Comment by dskvr** [comment]
Was resolved by removing `entry` from webpack, will need more robust configuration.
